sudo: false
language: node_js
node_js:
  - "stable"
  - "lts/*"
  - 10

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn run check:commit; fi'
  - yarn run check:lint
  - yarn run test:coverage
