language: node_js
node_js:
  - "stable"
  - "lts/*"
  - 10

cache: yarn

before_install:
  - npm --version
  - yarn --version

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn run check:commit; fi'
  - yarn run check:lint
  - yarn run test:coverage
